(async function(){
'use strict';var profile=await SupabaseDB.getCurrentProfile();if(profile.role!=='operator')return;var context=await SupabaseDB._rpc('manage_pricing',{p_action:'context'});if(!context.allowed)return;
function node(tag,text,parent){var e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(parent)parent.appendChild(e);return e;}
var root=node('details',undefined,document.body);root.className='operator-pricing';root.style.cssText='max-width:1160px;margin:20px auto;padding:18px;background:white;border:1px solid #dae4ed;border-radius:12px';node('summary','下级代理价格',root);node('p','未单独设置时沿用你的价格。优惠按你的价格计算，单项价格优先。',root);var select=node('select',undefined,root);context.agents.forEach(function(a){var o=node('option',a.name,select);o.value=a.id;});var status=node('p','',root),body=node('div',undefined,root);
function input(parent,label,type,value){var l=node('label',label,parent),i=node('input',undefined,l);i.type=type;i.value=value??'';i.style.cssText='padding:8px;margin:6px;border:1px solid #ccd8e1;border-radius:6px';return i;}
function button(parent,label,fn){var b=node('button',label,parent);b.onclick=async function(){b.disabled=true;try{await fn();status.textContent='已保存';}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};return b;}
async function save(action,data){return SupabaseDB._rpc('manage_pricing',{p_action:action,p_data:Object.assign({user_id:select.value},data)});}
async function load(){body.replaceChildren();status.textContent='正在加载，请稍后';try{var uid=select.value,data=await save('list',{});if(uid!==select.value)return;status.textContent='';body.replaceChildren();var pct=input(body,'整体优惠（%）','number',data.discount);pct.min=0;pct.max=100;pct.step='.01';button(body,'保存优惠',async function(){if(!pct.checkValidity())return pct.reportValidity();await save('agent',{discount:Number(pct.value)});});var search=input(body,'搜索配件','search',''),list=node('div',undefined,body);list.style.cssText='max-height:400px;overflow:auto';function render(){list.replaceChildren();data.items.filter(function(i){return i.label.includes(search.value);}).forEach(function(item){var row=node('div',undefined,list);row.style.cssText='padding:10px;border-bottom:1px solid #e3ebf1';node('span',item.label+' · 你的价格 '+item.base_price+' 元',row);var price=input(row,'代理单项价','number',item.override);price.min=0;price.step='.01';price.placeholder='跟随整体方案';button(row,'保存',async function(){if(!price.checkValidity())return price.reportValidity();await save(price.value===''?'remove_override':'override',{path:item.path,price:Number(price.value)});});});}search.oninput=render;render();}catch(e){status.textContent=e.message;}}
select.onchange=load;root.addEventListener('toggle',function(){if(root.open&&!body.children.length)load();});
})().catch(function(e){console.warn('下级价格设置：'+e.message);});
