(function(){
 'use strict';
 var db=SupabaseDB,conn=db.connection,profilePromise;
 function node(tag,text,parent){var n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.appendChild(n);return n;}
 function statusLabel(s){return {'打样中':'正在打样','已完成':'打样结束'}[s]||s;}
 function badge(s,parent){var n=node('span',statusLabel(s),parent);n.className='sample-status';n.dataset.status=s;return n;}
 function ready(){if(!profilePromise)profilePromise=db.getCurrentProfile();return profilePromise;}
 function canManage(p){return p.role==='admin'||(p.permissions||[]).includes('sample_manage')||(p.permissions||[]).includes('admin');}
 function button(parent,text,fn){var b=node('button',text,parent);b.type='button';b.onclick=fn;return b;}
 function dialog(title){var d=node('dialog',undefined,document.body);d.className='sample-ui sample-dialog';node('h2',title,d);var close=button(d,'关闭',function(){d.close();});close.style.cssText='float:right;margin-top:-42px';d.addEventListener('close',function(){d.remove();});d.showModal();return d;}
 async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('请选择15MB以内的图片');var b=await createImageBitmap(file),canvas=document.createElement('canvas'),ratio=Math.min(1,1600/Math.max(b.width,b.height));canvas.width=Math.round(b.width*ratio);canvas.height=Math.round(b.height*ratio);canvas.getContext('2d').drawImage(b,0,0,canvas.width,canvas.height);b.close();for(var q=.8;q>=.3;q-=.1){var blob=await new Promise(function(resolve){canvas.toBlob(resolve,'image/webp',q);});if(blob&&blob.size<=204800)return blob;}throw Error('图片细节过多，请裁剪后重试');}
 async function storage(path,method,body,type){var session=db.getSession();if(!session)throw Error('请重新登录');var res=await fetch(conn.url+'/storage/v1/object/'+path,{method:method,headers:{apikey:conn.publicKey,Authorization:'Bearer '+session.access_token,'Content-Type':type||'application/json'},body:body});if(!res.ok)throw Error('图片读取或上传失败，请检查权限后重试');return res;}
 async function clean(paths){if(paths.length)await storage('sample-images','DELETE',JSON.stringify({prefixes:paths}));}
 function field(form,name,label,type,required,max){var l=node('label',label,form),i=node(type==='textarea'?'textarea':'input',undefined,l);if(type!=='textarea')i.type=type;i.name=name;if(required)i.required=true;if(max)i.maxLength=max;if(type==='textarea')i.rows=5;return i;}
 async function sendResult(id){var session=db.getSession();if(!session)throw Error('请重新登录');var response;try{response=await fetch(conn.url+'/functions/v1/sample-delivery',{method:'POST',headers:{apikey:conn.publicKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({sample_id:id})});}catch(e){throw Error('打样已完成，邮件接口暂时无法连接；资料保留等待重试');}var data=await response.json();if(!response.ok)throw Error(data.error||'邮件服务尚未配置，资料保留等待重试');return data;}
 function changed(){window.dispatchEvent(new Event('samples-changed'));}
 async function openCreate(){var p=await ready(),d=dialog('添加打样'),form=node('form',undefined,d);form.id='sampleForm';form.className='sample-grid';var title=field(form,'title','样品名称','text',true,120);title.parentNode.className='sample-wide';var req=field(form,'requirements','打样需求','textarea',true,6000);req.placeholder='材料、加工位置、图案尺寸、深度、效果、交期与验收要求';req.parentNode.className='sample-wide';var name=field(form,'contact_name','联系人','text',true,100);name.value=p.full_name||p.username||'';var phone=field(form,'contact','联系电话','tel',true,200);phone.value=p.phone||'';field(form,'wechat','微信号','text',false,120);field(form,'carrier','快递公司','text',false,80);field(form,'tracking','快递单号（可稍后补充）','text',false,120);var photos=field(form,'images','参考图片','file');photos.accept='image/jpeg,image/png,image/webp';photos.multiple=true;photos.parentNode.className='sample-wide';node('span','最多5张，自动压缩后上传',photos.parentNode).className='sample-hint';var message=node('p','',form);message.className='sample-wide sample-error';message.setAttribute('role','status');var submit=node('button','保存打样',form);submit.type='submit';submit.className='primary';
 form.onsubmit=async function(e){e.preventDefault();submit.disabled=true;var uploaded=[],saved=false;try{var files=Array.from(photos.files);if(files.length>5)throw Error('最多上传5张图片');var id=crypto.randomUUID(),data=Object.fromEntries(new FormData(form));delete data.images;for(var file of files){var blob=await compress(file),path=p.id+'/'+id+'/'+crypto.randomUUID()+'.webp';await storage('sample-images/'+path,'POST',blob,'image/webp');uploaded.push(path);}data.images=uploaded;await db._rpc('create_sample',{p_id:id,p_data:data});saved=true;changed();d.close();}catch(err){if(!saved)try{await clean(uploaded);}catch(ignore){err.message+='；未使用的图片清理失败，请联系管理员';}message.textContent=err.message;}finally{submit.disabled=false;}};
 }
 async function get(id){var rows=await db._select('sample_requests','select=*&id=eq.'+encodeURIComponent(id)+'&limit=1');if(!rows[0])throw Error('样品不存在或无权查看');return rows[0];}
 async function detail(id,target){var p=await ready(),sample=await get(id),d=target||dialog('打样详情');var old=d.querySelector('.sample-detail');if(old)old.remove();var root=node('div',undefined,d);root.className='sample-detail';root.dataset.sampleId=id;badge(sample.status,root);node('h2',sample.title,root);var facts=node('div',undefined,root);facts.className='sample-facts';node('p','所属人：'+(sample.owner_name||'未填写'),facts);node('p','联系人：'+(sample.contact_name||sample.owner_name||'未填写'),facts);var phone=node('p','联系电话：',facts);var call=node('a',sample.contact,phone);call.href='tel:'+String(sample.contact).replace(/[^+\d-]/g,'');node('p','微信：'+(sample.wechat||'未填写'),facts);node('p','快递公司：'+(sample.carrier||'未填写'),facts);node('p','快递单号：'+(sample.tracking||'待寄送'),facts);node('h3','打样需求',root);node('div',sample.requirements,root).className='sample-requirements';node('h3','参考图片',root);var photos=node('div',undefined,root);photos.className='sample-photos';if(!(sample.images||[]).length)node('p','暂无参考图片',photos);if(!d.sampleImageCache){d.sampleImageCache=new Map();d.addEventListener('close',function(){d.sampleImageCache.forEach(URL.revokeObjectURL);d.sampleImageCache.clear();},{once:true});}
 for(var path of (sample.images||[]).concat(sample.result_images||[])){try{var url=d.sampleImageCache.get(path);if(!url){var response=await storage('authenticated/sample-images/'+path,'GET');url=URL.createObjectURL(await response.blob());if(!d.isConnected){URL.revokeObjectURL(url);continue;}d.sampleImageCache.set(path,url);}var img=node('img',undefined,photos);img.src=url;img.alt='打样参考图片（点击放大）';img.onclick=function(){var zoom=dialog('参考图片');zoom.classList.add('sample-image-dialog');var large=node('img',undefined,zoom);large.src=this.src;};}catch(e){node('p',e.message,photos).className='sample-error';}}
 var progress=node('section',undefined,root);progress.className='sample-progress';node('h3','打样进度',progress);if(sample.progress_note)node('p',sample.progress_note,progress);node('p',(sample.updated_by_name?'最近处理：'+sample.updated_by_name+' · ':'')+new Date(sample.updated_at||sample.created_at).toLocaleString(),progress).className='sample-hint';var error=node('p','',progress);error.className='sample-error';
 if(sample.status==='已完成'){node('p',sample.delivery_status||'等待发送结果邮件',progress);if(sample.delivery_error)node('p',sample.delivery_error,progress).className='sample-error';if(canManage(p))button(progress,'重试发送 / 清理',async function(){try{var result=await sendResult(id);changed();if(result.cleaned)d.close();else await detail(id,d);}catch(e){error.textContent=e.message;}});}
 if(canManage(p)&&sample.status!=='已完成'){var resultLabel=node('label','打样结果图片（最多5张）',progress),resultFiles=node('input',undefined,resultLabel);resultFiles.type='file';resultFiles.accept='image/jpeg,image/png,image/webp';resultFiles.multiple=true;var note=node('textarea',undefined,progress);note.placeholder='处理说明、加工结果或需要沟通的问题';note.maxLength=2000;note.rows=3;note.value=sample.progress_note||'';var actions=node('div',undefined,progress);actions.className='sample-actions';[['已收样','确认收样'],['打样中','正在打样'],['已完成','打样结束']].forEach(function(item){var b=button(actions,item[1],async function(){var buttons=Array.from(actions.querySelectorAll('button'));buttons.forEach(function(x){x.disabled=true;});try{if(item[0]==='已完成'){if(!note.value.trim())throw Error('请填写打样结果说明');var files=Array.from(resultFiles.files),uploaded=[];if(files.length+(sample.result_images||[]).length>5)throw Error('结果图片最多5张');try{for(var file of files){var blob=await compress(file),path=p.id+'/'+id+'/'+crypto.randomUUID()+'.webp';await storage('sample-images/'+path,'POST',blob,'image/webp');uploaded.push(path);}if(uploaded.length){var paths=(sample.result_images||[]).concat(uploaded);await db._rpc('save_sample_results',{p_id:id,p_images:paths});sample.result_images=paths;resultFiles.value='';}}catch(e){try{await clean(uploaded);}catch(_){}throw e;}}await db._rpc('set_sample_progress',{p_id:id,p_status:item[0],p_note:note.value.trim()});changed();if(item[0]==='已完成'){try{var result=await sendResult(id);if(result.cleaned){d.close();changed();return;}}catch(e){await detail(id,d);var target=d.querySelector('.sample-progress');node('p',e.message,target).className='sample-error';return;}}await detail(id,d);}catch(e){error.textContent=e.message;buttons.forEach(function(x){x.disabled=false;});}});b.className='primary';b.disabled=sample.status===item[0];});}
 if(sample.user_id===p.id&&sample.status!=='已完成'){var shipping=node('details',undefined,root);node('summary','补充 / 修改快递信息',shipping);var form=node('form',undefined,shipping);form.className='sample-grid';var carrier=field(form,'carrier','快递公司','text',false,80),tracking=field(form,'tracking','快递单号','text',false,120);carrier.value=sample.carrier;tracking.value=sample.tracking;var save=node('button','保存快递信息',form);save.type='submit';form.onsubmit=async function(e){e.preventDefault();save.disabled=true;try{await db._rpc('update_sample_shipping',{p_id:id,p_tracking:tracking.value,p_carrier:carrier.value});changed();await detail(id,d);}catch(e){error.textContent=e.message;save.disabled=false;}};}
 return d;
 }
 var columns='id,user_id,owner_name,title,contact_name,contact,wechat,carrier,tracking,status,created_at,updated_at,updated_by_name,delivery_status';
 window.SampleService={ready:ready,canManage:canManage,node:node,button:button,badge:badge,statusLabel:statusLabel,openCreate:openCreate,openDetail:detail,list:async function(options){options=options||{};var p=await ready(),query='select='+columns+'&order=created_at.desc&limit='+(options.limit||50)+'&offset='+(options.offset||0);if(options.own)query+='&user_id=eq.'+encodeURIComponent(p.id);if(options.status)query+='&status=eq.'+encodeURIComponent(options.status);return db._select('sample_requests',query);}};
})();
